apiVersion: v1
kind: Service
metadata:
    name: "aksesprit-b018"
    labels:
        app: "aksesprit-b018"
spec:
    type: LoadBalancer
    ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
    selector:
        app: "aksesprit-b018"